Trying to write assignments in Jupyter notebook for the first time

In [1]:
import numpy as np

In [6]:
sqrMt = [40,60,55,65,85,125,35,95,185,220]
rooms = [2,3,3,3,4,4,2,4,5,6]
price = [100,200,190,210,320,350,120,310,450,550]

In [3]:
all = np.array([sqrMt,rooms,price])

In [4]:
all = np.transpose(all)

In [5]:
print("\nthe array has the information of",np.shape(all)[0],"houses with",np.shape(all)[1],"features on every line")
print(all)


the array has the information of 10 houses with 3 features on every line
[[ 40   2 100]
 [ 60   3 200]
 [ 55   3 190]
 [ 65   3 210]
 [ 85   4 320]
 [125   4 350]
 [ 35   2 120]
 [ 95   4 310]
 [185   5 450]
 [220   6 550]]


In [9]:
rows = int(input("input number of rows:"))
columns = int(input("input number of columns:"))
new = np.ones([rows,columns])
new[1:np.shape(new)[0]:2, 1:np.shape(new)[1]:2] = 0
print("\nmatrix of ones with zeros on where rows and columns are both even\n",new)

input number of rows: 9
input number of columns: 6



matrix of ones with zeros on where rows and columns are both even
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1.]]
